export const eng = {
  login: "Login",
  mobile: "Mobile Number",
  entermobilenumber: "Enter Your Mobile Number",
  sendotp: "Send Otp",
  enterotp: "Please Enter Your OTP",
  signin: "Sign In",
  location: "Location",
  locationcontent: "Allow access to Location to provide you the best relevant features on this App such as",
  giveaccess: "Give Access",
  skip: "Skip",
  whoru: "Who are you?",
  typedescription: "Choose Who Describes you the best",
  next: "Next",
  selectcrop: "Select Crop",
  cropdescription: "Select up to 8 crops of your interest",
  locnotification: "Notifications of nearby Crops Planted",
  weatherupdate: " Weather updates",
  pestanddiseases: "Pest & Diseases",
  pestcontent: "Know about pest & deseases related to your crop",
  fertilizercalc: "Fertilizer Calculator",
  fertilizercontent: "Calculate the amount of Fertilizer required",
  instructions: "Instructions",
  instructionscontent: "Choose What Describes you the best",
  steps: "Steps",
  cropcontent: "Check the health of your crop and ensure it is fine. Perform the following steps",
  cameracontent: "Go close to the plant and take a clear picture of the affected area. If healthy, take a clear photo in good light.",
  uploadcontent: "Upload the image to the site. You will see a list of possible diseases and symptoms.",
  recommendationContent: "Check the recommended treatments from our dealers. Go to the map to find the nearest dealer.",
  answer: "Improve the Probability of receiving the right answer.",
  addcrop: "Add Crop",
  question: "Your question to the community",
  questionplaceholder: "Add a question indicating what's wrong with your crop",
  description: "Description of your problem",
  descriptionplaceholder: "Describe specialities such as change of leaves,roots,color,bugs,tears..."
};

export const hin = {
  login: "लॉग इन करें",
  mobile: "मोबाइल नंबर",
  entermobilenumber: "अपना मोबाइल नंबर दर्ज करें",
  sendotp: "OTP भेजें",
  enterotp: "कृपया अपना ओटीपी दर्ज करें",
  signin: "साइन इन करें",
  location: "स्थान",
  locationcontent:
    "आपको इस ऐप जैसे सर्वोत्तम प्रासंगिक सुविधाएं प्रदान करने के लिए स्थान तक पहुंच की अनुमति दें",
  giveaccess: "पहुँच दे",
  skip: "छोड़ें",
  whoru: "तुम कौन हो??",
  typedescription: "चुनें कि कौन आपको सबसे अच्छा बताता है",
  next: "आगे",
  selectcrop: "फसल का चयन करें",
  cropdescription: "अपनी रुचि के 8 फसलों तक का चयन करें",
  locnotification: "पास की फसलों की अधिसूचनाएँ",
  weatherupdate: " मौसम का अपडेट",
  pestanddiseases: "कीट और रोग",
  pestcontent: "अपनी फसल से संबंधित कीट और रोगों के बारे में जानें",
  fertilizercalc: "उर्वरक कैलकुलेटर",
  fertilizercontent: "आवश्यक उर्वरक की मात्रा की गणना करें",
  instructions: "अनुदेश",
  instructionscontent: "क्या आप सबसे अच्छा वर्णन करता है चुनें",
  steps: "कदम",
  cropcontent: "अपनी फसल के स्वास्थ्य की जांच करें और सुनिश्चित करें कि यह ठीक है। निम्न चरणों का पालन करें",
  cameracontent: "पौधे के करीब जाएं और प्रभावित क्षेत्र की स्पष्ट तस्वीर लें। यदि स्वस्थ हैं, तो अच्छी रोशनी में एक स्पष्ट फोटो लें।",
  uploadcontent: "छवि को साइट पर अपलोड करें। आप संभावित रोगों और लक्षणों की एक सूची देखेंगे।",
  recommendationContent: "हमारे डीलरों से अनुशंसित उपचार देखें। निकटतम डीलर को खोजने के लिए मानचित्र पर जाएं।",
  answer: "सही उत्तर प्राप्त करने की संभावना में सुधार करें।",
  addcrop: "फसल जोड़ें",
  question: "समुदाय के लिए आपका प्रश्न",
  questionplaceholder: "एक प्रश्न जोड़ें जो यह दर्शाता है कि आपकी फसल में क्या गलत है",
  description: "आपकी समस्या का वर्णन",
  descriptionplaceholder: "पत्तियों, जड़ों, रंग, कीड़े, आँसू के परिवर्तन जैसे विशेषणों का वर्णन करें ..."
};

export const tel = {
  login: "ప్రవేశించండి",
  mobile: "మొబైల్ సంఖ్య",
  entermobilenumber: "మీ మొబైల్ నెంబర్ ను ఎంటర్ చేయండి",
  sendotp: "OTP పంపండి",
  enterotp: "దయచేసి మీ OTP ని నమోదు చేయండి",
  signin: "సైన్ ఇన్ చేయండి",
  location: "స్థానం",
  locationcontent:
    "వంటి ఈ అనువర్తనంలో మీకు ఉత్తమమైన లక్షణాలను అందించడానికి స్థానానికి ప్రాప్యతను అనుమతించండి",
  giveaccess: "యాక్సెస్ ఇవ్వండి",
  skip: "స్కిప్",
  whoru: "నీవెవరు?",
  typedescription: "మిమ్మల్ని ఎవరు ఉత్తమంగా వివరిస్తారో ఎంచుకోండి",
  next: "తరువాత",
  selectcrop: "పంటను ఎంచుకోండి",
  cropdescription: "మీకు ఆసక్తి ఉన్న 8 పంటలను ఎంచుకోండి",
  locnotification: "సమీప పంటల నోటిఫికేషన్లు",
  weatherupdate: "వాతావరణ నవీకరణలు",
  pestanddiseases: "తెగులు & వ్యాధులు",
  pestcontent: "మీ పంటకు సంబంధించిన పెస్ట్ & డీసీసెస్ గురించి తెలుసుకోండి",
  fertilizercalc: "ఎరువుల కాలిక్యులేటర్",
  fertilizercontent: "అవసరమైన ఎరువుల మొత్తాన్ని లెక్కించండి",
  instructions: "సూచనలు",
  instructionscontent: "మీకు ఉత్తమంగా వివరించేదాన్ని ఎంచుకోండి",
  steps: "స్టెప్స్",
  cropcontent: "మీ పంట ఆరోగ్యాన్ని తనిఖీ చేయండి మరియు అది బాగానే ఉందని నిర్ధారించుకోండి. కింది దశలను చేయండి",
  cameracontent: "మొక్క దగ్గరకు వెళ్లి ప్రభావిత ప్రాంతం గురించి స్పష్టమైన చిత్రాన్ని తీయండి. ఆరోగ్యంగా ఉంటే, మంచి కాంతిలో స్పష్టమైన ఫోటో తీయండి.",
  uploadcontent: "చిత్రాన్ని సైట్‌కు అప్‌లోడ్ చేయండి. మీరు సాధ్యమయ్యే వ్యాధులు మరియు లక్షణాల జాబితాను చూస్తారు.",
  recommendationContent: "మా డీలర్ల నుండి సిఫార్సు చేయబడిన చికిత్సలను తనిఖీ చేయండి. సమీప డీలర్‌ను కనుగొనడానికి మ్యాప్‌కు వెళ్లండి.",
  answer: "సరైన సమాధానం స్వీకరించే సంభావ్యతను మెరుగుపరచండి.",
  addcrop: "పంట జోడించండి",
  question: "సంఘానికి మీ ప్రశ్న",
  questionplaceholder: "మీ పంటలో ఏది తప్పు అని సూచించే ప్రశ్నను జోడించండి",
  description: "మీ సమస్య యొక్క వివరణ",
  descriptionplaceholder: "ఆకులు, మూలాలు, రంగు, దోషాలు, కన్నీళ్లు వంటి ప్రత్యేకతలను వివరించండి ..."
};
